apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- pvc.yaml
# - secret.yaml  # not needed when model is locally sourced
- deployment.yaml
- service.yaml

namespace: example-prokube

images:
  - name: DUMMY_IMAGE
    newName: repo/image
    newTag: latest  # optional; omit if it's already in the name
