apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-cpu-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
  volumeMode: Filesystem
