apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  selector:
    app: vllm-cpu
  ports:
    - protocol: TCP
      name: http-vllm-cpu
      port: 80
      targetPort: 8000 # Must match the container's exposed port
  sessionAffinity: None
  type: ClusterIP
