apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ .Values.model.name }}-inference
spec:
  selector:
    matchLabels:
      app: {{ .Values.model.name }}
  action: ALLOW
  rules:
    - to:
        - operation:
            paths: ["/vllm-serving/{{ .Values.model.endpointPath }}/"]
