apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.model.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.model.pvcSize }}
  storageClassName: {{ .Values.model.storageClassName }}
  volumeMode: Filesystem
