{{- if and .Values.HF_API_TOKEN (ne .Values.HF_API_TOKEN "dummy") }}
apiVersion: v1
kind: Secret
metadata:
  name: hf-api-token
data:
  HF_API_TOKEN: {{ .Values.HF_API_TOKEN | b64enc }}
{{- end }}
