apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.model.name }}
spec:
  ports:
    - name: http-{{ .Values.model.name }}
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ .Values.model.name }}
  sessionAffinity: None
  type: ClusterIP
